### PR TITLE
[Refactor: RainbowGrades] Academic sanction

### PR DESCRIPTION
**Pull request by RitaLei123**
Closes https://github.com/Submitty/Submitty/issues/9725
Changed all the mossify and moss instances to academic_sanction in three documents (main.cpp, student.cpp, student.h) in the Rainbow Grades directory. These changes were made to avoid potential copyright issues.  

image

### CODE REVIEW

**Review by ziesski — CHANGES_REQUESTED** [review]
I see you changed moss -> academic_sanction as well, but there are some files that you have missed, and it will not compile correctly. For example check output.cpp line 949 still has getmosspenalty. Please be more careful when replacing terms, as it may be used more broadly.

**Comment by RitaLei123** [comment]
> I see you changed moss -> academic_sanction as well, but there are some files that you have missed, and it will not compile correctly. For example check output.cpp line 949 still has getmosspenalty. Please be more careful when replacing terms, as it may be used more broadly.

**Comment by RitaLei123** [comment]
> I see you changed moss -> academic_sanction as well, but there are some files that you have missed, and it will not compile correctly. For example check output.cpp line 949 still has getmosspenalty. Please be more careful when replacing terms, as it may be used more broadly.

image

I have fixed those all the cases and doubled checked everything. There should be no more moss instances now. Sorry, I will be more careful in the future.

**Review by ziesski — APPROVED** [review]
It looks good, I reviewed the code, and also tested locally. 
One thing to comment is we have student.cpp patch going on, so I think we should merge this after the patch gets merged to reduce merge conflict.

**Pull request merged**
