### PR TITLE
[RainbowGrades:Feature] add display options

### PR DESCRIPTION
**Pull request by ziesski**
Currently in web-based customization page, we have display option, which is acts like a switch to enable and disable contents that needs to be displayed to students. There are currently 7 options, which are available, but we will expand these features to 14 options. It is a valid checkbox on the Web GUI, but RainbowGrades cannot take the new 7 options, and will silently break if the new options are checked. Hence, this PR will fix it by adding a placeholder to handle additional tokens in display options.

### CODE REVIEW

**Review by taorif25 — APPROVED** [review]
Changes are minimal and prevent the OOPS messages from being displayed. Good temporary fix until the features are implemented.

**Comment by williamjallen** [comment]
@ziesski Can you add additional information to the PR description?  Right now, it's hard to tell what this PR does based on the description alone.  The PR description is the most important documentation available for future developers who may happen to run across this PR in the future.

**Comment by ziesski** [comment]
@williamjallen Yup, I just did. Please check :)

**Comment by williamjallen** [comment]
Thanks!

**Review by bmcutler — APPROVED** [review]

**Pull request merged**
