### PR TITLE
[Refactor:RainbowGrades] Remove benchmark_percent from display

### PR DESCRIPTION
**Pull request by ziesski**
Matching behavior of Submitty Repo

### CODE REVIEW

**Comment by micpap25** [comment]
I don't think this is sufficient, for example look at line 568 of `main.cpp`. I think we could remove more references to it.

**Comment by ziesski** [comment]
> I don't think this is sufficient, for example look at line 568 of `main.cpp`. I think we could remove more references to it.

No, "benchmark_percent" that you are referring to is an independent token that should not get removed, which in fact is used to display benchmark percent (yes bad naming choice), we are trying to address benchmark_percent tag living inside of display token.

**Review by micpap25 — APPROVED** [review]

**Comment by micpap25** [comment]
> > I don't think this is sufficient, for example look at line 568 of `main.cpp`. I think we could remove more references to it.
> 
> No, "benchmark_percent" that you are referring to is an independent token that should not get removed, which in fact is used to display benchmark percent (yes bad naming choice), we are trying to address benchmark_percent tag living inside of display token.

Would it be possible to change the name? If not I understand

**Comment by zacharymnp** [comment]
Removing the benchmark_percent tag inside of display should make changing the name of the other benchmark_percent redundant, since there will only be one token named benchmark_percent.

**Pull request merged**
