### PR TITLE
[Feature:RainbowGrades] Display RainbowGrades version

### PR DESCRIPTION
**Pull request by ziesski**
This update allows all users of RainbowGrades (i.e. instructors and students) to see the build version at the bottom of the RainbowGrades page. This version info is vital as it allows instructors to know which version they are currently using.

Having this version information readily available will enable instructors to provide accurate details when reporting any issues or errors they encounter. In turn, developers can use this version information to identify any potential discrepancies caused by outdated versions and assist instructors more efficiently in resolving their concerns.

[Instructor view]
Screen Shot 2023-07-28 at 11 49 10 AM

[student view]
Screen Shot 2023-07-28 at 1 39 52 PM

### CODE REVIEW

**Comment by ziesski** [comment]
#closes/Submitty/Submitty/issues/9492

**Comment by ziesski** [comment]
It may be causing error when ran on web-base-customization page
fatal: detected dubious ownership in repository at '/usr/local/submitty/GIT_CHECKOUT/RainbowGrades'
To add an exception for this directory, call:
	git config --global --add safe.directory /usr/local/submitty/GIT_CHECKOUT/RainbowGrades

Will fix it

**Review by ziesski — COMMENTED** [review]
It may be causing error when ran on web-base-customization page
fatal: detected dubious ownership in repository at '/usr/local/submitty/GIT_CHECKOUT/RainbowGrades'
To add an exception for this directory, call:
	git config --global --add safe.directory /usr/local/submitty/GIT_CHECKOUT/RainbowGrades

Will fix it

**Review by ziesski — COMMENTED** [review]
In addition to safe directory, we need to give submitty_daemon_php group read permission in /etc/gitconfig file.

**Comment by ziesski** [comment]
Resolved merge conflict

**Review by bmcutler — APPROVED** [review]
I tested this on my mac.  I had to change the path where the RG_version is written.  The original code made assumptions about the directory on the instructor's machine.  

Before we merge this, please re-test that it works on the server with the nightly build with the replaced path.  AND please get someone to test that it works on a Mac installation (I'm not sure that the environment variables syntax is compatible on all platforms).

**Comment by bmcutler** [comment]
@ziesski 
Please see my note above

**Review by oliiso — APPROVED** [review]
Looks good, reviewed this on my mac.

**Review by zacharymnp — APPROVED** [review]
Works on Windows 10
image

**Pull request merged**
